/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui.manager;

import dao.impl.NhanVienDAOImpl;
import entity.NhanVien;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.XJdbc;

/**
 *
 * @author 
 */
public class QuanLyNhanVien extends javax.swing.JDialog {
    
    /**
     * Creates new form QuanLyNhanVien
     */
    public QuanLyNhanVien(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        
        
        
        //Set Bảng không cho thay đổi thông tin
            DefaultTableModel model = new DefaultTableModel(
            new Object[][]{},
            new String[]{"Mã Nhân Viên", "Tên Nhân Viên", "SĐT", "Chức Vụ", "Lương", "Số Ngày Làm", "Số Ngày Nghỉ", "Tên Đăng Nhập"}
            ) {
            @Override
            public boolean isCellEditable(int row, int column) {
            return false;
            }
            };
            tblBangNhanVien.setModel(model);
            
            
            
    fillToTable();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBangNhanVien = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtChucVu = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtLuong = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNgayLam = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNgayNghi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTenDangNhap = new javax.swing.JTextField();
        btnLamMoi = new javax.swing.JButton();
        btnThemNhanVien = new javax.swing.JButton();
        btnCapNhatThongTin = new javax.swing.JButton();
        btnXoaNhanVien = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblBangNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Tên Nhân Viên", "SĐT", "Chức Vụ", "Lương", "Số Ngày Làm", "Số Ngày Nghỉ", "Tên Đăng Nhập"
            }
        ));
        tblBangNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBangNhanVien);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tìm Kiếm:");

        btnSearch.setText("Tìm Kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Quản Lý Nhân Viên ", jPanel1);

        jLabel3.setText("Mã Nhân Viên:");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        jLabel4.setText("Tên Nhân Viên:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        jLabel5.setText("Số Điện Thoại:");

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });

        jLabel6.setText("Chức Vụ:");

        txtChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChucVuActionPerformed(evt);
            }
        });

        jLabel7.setText("Lương:");

        txtLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLuongActionPerformed(evt);
            }
        });

        jLabel8.setText("Số Ngày Làm:");

        txtNgayLam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayLamActionPerformed(evt);
            }
        });

        jLabel9.setText("Số Ngày Nghỉ:");

        txtNgayNghi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayNghiActionPerformed(evt);
            }
        });

        jLabel10.setText("Tên Đăng Nhập:");

        txtTenDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenDangNhapActionPerformed(evt);
            }
        });

        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnThemNhanVien.setText("Thêm Nhân Viên");
        btnThemNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNhanVienActionPerformed(evt);
            }
        });

        btnCapNhatThongTin.setText("Cập Nhật Thông Tin");
        btnCapNhatThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatThongTinActionPerformed(evt);
            }
        });

        btnXoaNhanVien.setText("Xóa Nhân Viên");
        btnXoaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtNgayLam, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtNgayNghi, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(238, 238, 238))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnLamMoi)
                .addGap(18, 18, 18)
                .addComponent(btnThemNhanVien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCapNhatThongTin)
                .addGap(18, 18, 18)
                .addComponent(btnXoaNhanVien)
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNgayLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNgayNghi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapNhatThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Biểu Mẫu ", jPanel2);

        getContentPane().add(TabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 920, 460));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hinhnen.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        searchNhanVien();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChucVuActionPerformed

    private void txtLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLuongActionPerformed

    private void txtNgayLamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayLamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayLamActionPerformed

    private void txtNgayNghiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayNghiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayNghiActionPerformed

    private void txtTenDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenDangNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenDangNhapActionPerformed

    private void tblBangNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangNhanVienMouseClicked
        // TODO add your handling code here:
    tblBangNhanVien.addMouseListener(new MouseAdapter() {
    @Override
    public void mouseClicked(MouseEvent e) {
        int selectedRow = tblBangNhanVien.getSelectedRow();
        if (selectedRow != -1) {
            txtID.setText(tblBangNhanVien.getValueAt(selectedRow, 0).toString());
            txtName.setText(tblBangNhanVien.getValueAt(selectedRow, 1).toString());
            txtPhone.setText(tblBangNhanVien.getValueAt(selectedRow, 2).toString());
            txtChucVu.setText(tblBangNhanVien.getValueAt(selectedRow, 3).toString());
            txtLuong.setText(tblBangNhanVien.getValueAt(selectedRow, 4).toString());
            txtNgayLam.setText(tblBangNhanVien.getValueAt(selectedRow, 5).toString());
            txtNgayNghi.setText(tblBangNhanVien.getValueAt(selectedRow, 6).toString());
            txtTenDangNhap.setText(tblBangNhanVien.getValueAt(selectedRow, 7).toString());

            // Khóa các trường không cho phép sửa
            txtID.setEditable(false);
            txtName.setEditable(false);
            txtNgayLam.setEditable(false);
            txtNgayNghi.setEditable(false);
            txtTenDangNhap.setEditable(false);

            // Mở các trường được phép sửa
            txtPhone.setEditable(true);
            txtChucVu.setEditable(true);
            txtLuong.setEditable(true);

            // ✅ Chuyển qua tab "Biểu Mẫu"
            TabbedPane.setSelectedIndex(1);  // <-- CHỈNH LẠI THÀNH 1
        }
    }
});

    }//GEN-LAST:event_tblBangNhanVienMouseClicked

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        btnLamMoi.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        // Xóa trắng tất cả các ô nhập
        txtID.setText("");
        txtName.setText("");
        txtPhone.setText("");
        txtChucVu.setText("");
        txtLuong.setText("");
        txtNgayLam.setText("");
        txtNgayNghi.setText("");
        txtTenDangNhap.setText("");

        // ✅ Mở khóa tất cả các trường nhập
        txtID.setEditable(true);
        txtName.setEditable(true);
        txtPhone.setEditable(true);
        txtChucVu.setEditable(true);
        txtLuong.setEditable(true);
        txtNgayLam.setEditable(true);
        txtNgayNghi.setEditable(true);
        txtTenDangNhap.setEditable(true);

        // ✅ (Tùy chọn) Chuyển sang tab Biểu Mẫu
        TabbedPane.setSelectedIndex(1); // Nếu tab Biểu Mẫu ở vị trí số 1
    }
});

    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnThemNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNhanVienActionPerformed
        // TODO add your handling code here:
        themNhanVien();
    }//GEN-LAST:event_btnThemNhanVienActionPerformed

    private void btnCapNhatThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatThongTinActionPerformed
        // TODO add your handling code here:
        capNhatNhanVien();
    }//GEN-LAST:event_btnCapNhatThongTinActionPerformed

    private void btnXoaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNhanVienActionPerformed
        // TODO add your handling code here:
        xoaNhanVien();
    }//GEN-LAST:event_btnXoaNhanVienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanLyNhanVien dialog = new QuanLyNhanVien(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JButton btnCapNhatThongTin;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnThemNhanVien;
    private javax.swing.JButton btnXoaNhanVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBangNhanVien;
    private javax.swing.JTextField txtChucVu;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNgayLam;
    private javax.swing.JTextField txtNgayNghi;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTenDangNhap;
    // End of variables declaration//GEN-END:variables
public void fillToTable() {
    DefaultTableModel model = (DefaultTableModel) tblBangNhanVien.getModel();
    model.setRowCount(0); 

    String sql = "SELECT * FROM NHANVIEN";

    try {
        ResultSet rs = XJdbc.executeQuery(sql);
        while (rs.next()) {
            Object[] row = new Object[]{
                rs.getInt("MaNV"),
                rs.getNString("TenNV"),
                rs.getString("SDT"),
                rs.getNString("ChucVu"),
                rs.getDouble("Luong"),
                rs.getInt("SoNgayLam"),
                rs.getInt("SoNgayNghi"),
                rs.getString("TenDangNhap")
            };
            model.addRow(row);
        }
        rs.getStatement().getConnection().close(); // Đóng kết nối nếu XJdbc không tự xử lý
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi truy vấn dữ liệu nhân viên!");
    }
}
public void searchNhanVien() {
    String keyword = txtSearch.getText().trim(); // ô nhập liệu
    DefaultTableModel model = (DefaultTableModel) tblBangNhanVien.getModel();
    model.setRowCount(0); // xóa bảng trước khi load lại

    if (keyword.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Vui lòng nhập mã hoặc tên nhân viên cần tìm!");
        return;
    }

    List<NhanVien> list = new ArrayList<>();
    NhanVienDAOImpl dao = new NhanVienDAOImpl();

    try {
        int maNV = Integer.parseInt(keyword);
        list = dao.selectBySql(
            "SELECT * FROM NHANVIEN WHERE MaNV = ? OR TenNV LIKE ?",
            maNV, "%" + keyword + "%"
        );
    } catch (NumberFormatException e) {
        list = dao.selectBySql(
            "SELECT * FROM NHANVIEN WHERE TenNV LIKE ?",
            "%" + keyword + "%"
        );
    }

    if (list.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Không tìm thấy nhân viên phù hợp!");
        return;
    }

    for (NhanVien nv : list) {
        model.addRow(new Object[]{
            nv.getMaNV(),
            nv.getTenNV(),
            nv.getSdt(),
            nv.getChucVu(),
            nv.getLuong(),
            nv.getSoNgayLam(),
            nv.getSoNgayNghi(),
            nv.getTenDangNhap()
        });
    }
}
public void themNhanVien() {
    String name = txtName.getText().trim();
    String phone = txtPhone.getText().trim();
    String chucVu = txtChucVu.getText().trim();
    String luong = txtLuong.getText().trim();
    String ngayLam = txtNgayLam.getText().trim();
    String ngayNghi = txtNgayNghi.getText().trim();
    String tenDangNhap = txtTenDangNhap.getText().trim();

    if (name.isEmpty() || phone.isEmpty() || chucVu.isEmpty()
            || luong.isEmpty() || ngayLam.isEmpty() || ngayNghi.isEmpty() || tenDangNhap.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
        return;
    }

    try {
        String sql = "INSERT INTO NhanVien (TenNV, Sdt, ChucVu, Luong, SoNgayLam, SoNgayNghi, TenDangNhap) "
                   + "VALUES (?, ?, ?, ?, ?, ?, ?)";
        int rows = XJdbc.update(sql, name, phone, chucVu,
                                Double.parseDouble(luong),
                                Integer.parseInt(ngayLam),
                                Integer.parseInt(ngayNghi),
                                tenDangNhap);

        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Thêm nhân viên vào CSDL thành công!");
            fillToTable(); // Load lại bảng hiển thị
            btnLamMoi.doClick(); // Xoá form
        }
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi thêm vào CSDL!");
    }
}

public void capNhatNhanVien() {
    int selectedRow = tblBangNhanVien.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần cập nhật!");
        return;
    }

    String id = txtID.getText().trim();
    String phone = txtPhone.getText().trim();
    String chucVu = txtChucVu.getText().trim();
    String luong = txtLuong.getText().trim();

    if (phone.isEmpty() || chucVu.isEmpty() || luong.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Không được để trống các trường được chỉnh sửa!");
        return;
    }

    try {
        String sql = "UPDATE NhanVien SET Sdt = ?, ChucVu = ?, Luong = ? WHERE MaNV = ?";
        int rows = XJdbc.update(sql, phone, chucVu, Double.parseDouble(luong), id);

        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
            fillToTable(); // Load lại bảng
        }
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật vào CSDL!");
    }
}
public void xoaNhanVien() {
    String id = txtID.getText().trim();

    if (id.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần xóa!");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this,
            "Bạn có chắc muốn xóa nhân viên có mã: " + id + "?", 
            "Xác nhận", 
            JOptionPane.YES_NO_OPTION);

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    try {
        String sql = "DELETE FROM NhanVien WHERE MaNV = ?";
        int rows = XJdbc.update(sql, Integer.parseInt(id));

        if (rows > 0) {
            JOptionPane.showMessageDialog(this, "Xóa nhân viên thành công!");
            fillToTable(); // Refresh bảng
            btnLamMoi.doClick(); // Reset biểu mẫu
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên để xóa.");
        }
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi xóa nhân viên!");
    }
}


}
